name: nirfasgpstracker
description: A Flutter app to track device location using OpenStreetMap and HTTP.

publish_to: "none" # Removes the possibility to accidentally publish the app to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0 # For fetching location data from server
  flutter_map: ^6.0.0 # For OpenStreetMap integration
  latlong2: ^0.9.0 # For LatLng support in flutter_map
  # Add any other dependencies your app needs here

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    # Add your assets here if you have any (like images, icons, etc.)
    # Example:
    # - assets/images/
    # - assets/icons/
